export default {
  maxexpandId: 95,
  treelist: [{
    id: 1,
    name: '北京市',
    ProSort: 1,
    remark: '直辖市',
    pid: '',
    isEdit: false,
    children: [{
      id: 35,
      name: '朝阳区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 36,
      name: '海淀区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 37,
      name: '房山区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 38,
      name: '丰台区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 39,
      name: '昌平区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 40,
      name: '大兴区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }]
  }, {
    id: 2,
    name: '天津市',
    ProSort: 2,
    remark: '直辖市',
    pid: '',
    isEdit: false,
    children: [{
      id: 41,
      name: '北辰区',
      pid: 2,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 42,
      name: '河北区',
      pid: 2,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 43,
      name: '西青区',
      pid: 2,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 44,
      name: '东丽区',
      pid: 2,
      remark: '',
      isEdit: false,
      children: []
    }]
  }, {
    id: 3,
    name: '河北省',
    ProSort: 5,
    remark: '省份',
    pid: '',
    isEdit: false,
    children: [{
      id: 45,
      name: '衡水市',
      pid: 3,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 46,
      name: '张家口市',
      pid: 3,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 47,
      name: '秦皇岛市',
      pid: 3,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 48,
      name: '承德市',
      pid: 3,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 49,
      name: '邯郸市',
      pid: 3,
      remark: '',
      isEdit: false,
      children: []
    }]
  }, {
    id: 4,
    name: '山西省',
    ProSort: 6,
    remark: '省份',
    pid: '',
    isEdit: false,
    children: [{
      id: 50,
      name: '大同市',
      pid: 4,
      remark: '',
      isEdit: false,
      children: []
    }]
  }, {
    id: 5,
    name: '内蒙古自治区',
    ProSort: 32,
    remark: '自治区',
    pid: '',
    isEdit: false,
    children: [{
      id: 51,
      name: '包头市',
      pid: 5,
      remark: '',
      isEdit: false,
      children: []
    }]
  }, {
    id: 6,
    name: '辽宁省',
    ProSort: 8,
    remark: '省份',
    pid: '',
    isEdit: false,
    children: [{
      id: 52,
      name: '大连市',
      pid: 6,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 53,
      name: '太原市',
      pid: 6,
      remark: '',
      isEdit: false,
      children: []
    }]
  }, {
    id: 20,
    name: '海南省',
    ProSort: 24,
    remark: '省份',
    pid: '',
    isEdit: false,
    children: [{
      id: 68,
      name: '海口市',
      pid: 20,
      remark: '',
      isEdit: false,
      children: []
    }]
  }, {
    id: 21,
    name: '广西壮族自治区',
    ProSort: 28,
    remark: '自治区',
    pid: '',
    isEdit: false,
    children: [{
      id: 69,
      name: '玉林市',
      pid: 21,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 86,
      name: '贺州市',
      pid: 21,
      remark: '',
      isEdit: false,
      children: []
    }]
  }, {
    id: 22,
    name: '甘肃省',
    ProSort: 21,
    remark: '省份',
    pid: '',
    isEdit: false,
    children: [{
      id: 70,
      name: '兰州市',
      pid: 22,
      remark: '',
      isEdit: false,
      children: []
    }]
  }, {
    id: 23,
    name: '陕西省',
    ProSort: 27,
    remark: '省份',
    pid: '',
    isEdit: false,
    children: [{
      id: 71,
      name: '咸阳市',
      pid: 23,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 87,
      name: '安康市',
      pid: 23,
      remark: '',
      isEdit: false,
      children: []
    }]
  }, {
    id: 24,
    name: '新疆维吾尔自治区',
    ProSort: 31,
    remark: '自治区',
    pid: '',
    isEdit: false,
    children: [{
      id: 72,
      name: '乌鲁木齐市',
      pid: 24,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 88,
      name: '和田地区',
      pid: 24,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 89,
      name: '阿勒泰州',
      pid: 24,
      remark: '',
      isEdit: false,
      children: []
    }]
  }, {
    id: 25,
    name: '青海省',
    ProSort: 26,
    remark: '省份',
    pid: '',
    isEdit: false,
    children: [{
      id: 73,
      name: '黄南藏族自治州',
      pid: 25,
      remark: '',
      isEdit: false,
      children: []
    }]
  }, {
    id: 26,
    name: '宁夏回族自治区',
    ProSort: 30,
    remark: '自治区',
    pid: '',
    isEdit: false,
    children: [{
      id: 74,
      name: '银川市',
      pid: 26,
      remark: '',
      isEdit: false,
      children: []
    }]
  }]
}
